alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias all='ansible-playbook -i /etc/ansible/inventory --ask-become-pass'
alias big10='find . -type f -print0 | xargs -0 du -h | sort -hr | head -10'
alias e='sudo nano '
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias filesizes='ls -laSh'
alias grep='grep -i'
alias hgrep='history | grep'
alias i='sudo apt install'
alias ipa='ip a | grep 192'
alias l='ls -CF'
alias la='ls -A'
alias lgrep='ls | grep'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias publicip='curl ifconfig.me'
alias qflip='~/Downloads/qFlipper-x86_64-1.2.2.AppImage'
alias show-wifi='nmcli device wifi show-password'
alias smbmount='sudo mount -t cifs -o username=greyson //192.168.4.43/homes /mnt/Whiterun'
alias steam='GDK_SCALE=2 steam'
alias vpn-down='sudo wg-quick down /etc/wireguard/riverwood.conf'
alias vpn-up='sudo wg-quick up /etc/wireguard/riverwood.conf'
